// Copyright 2025 - See NOTICE file for copyright holders.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#![cfg(test)]

use {alloy_primitives::keccak256, solana_sdk::secp256k1_recover::secp256k1_recover};

#[tokio::test]
async fn test_signature_verification_secp256k1() {
    // Test if Eth-backend-generated signature verifies if:
    // - participant with public key is randomly generated by perun-eth-backend in go
    // - message is signed by the participant's account in the perun-eth-backend, generating a signature
    // - the generated signature, as well as the message are used to recover the participant's public key and verify that it is identical to the signer's key

    // Message
    let message = b"hello world";
    let msg_hash = keccak256(message);
    let hash_bytes: [u8; 32] = msg_hash.into();

    let prefix = b"\x19Ethereum Signed Message:\n32";
    let prefix_hash = [prefix.as_ref(), &hash_bytes[..]].concat();
    let prefixhash_slice: &[u8] = prefix_hash.as_slice();
    let hashed_msg_with_prefix = keccak256(prefixhash_slice);

    let sig: [u8; 64] = [
        16, 17, 239, 225, 176, 41, 232, 223, 159, 227, 117, 129, 82, 28, 153, 222, 0, 156, 90, 210,
        67, 185, 127, 194, 165, 8, 234, 127, 220, 3, 105, 94, 18, 93, 100, 241, 189, 4, 20, 55,
        186, 7, 117, 147, 234, 132, 47, 149, 229, 167, 190, 28, 10, 24, 140, 100, 240, 13, 82, 171,
        238, 2, 111, 69,
    ]; // 28,
    let recovery_id: u8 = 1; // 0 or 1 for Ethereum

    let pubkey: [u8; 65] = [
        4, 102, 214, 214, 113, 6, 75, 129, 66, 93, 131, 63, 72, 125, 19, 123, 3, 101, 142, 161,
        232, 30, 54, 48, 40, 7, 153, 40, 167, 169, 110, 125, 109, 87, 40, 52, 175, 161, 196, 43,
        104, 153, 202, 94, 107, 143, 82, 133, 139, 163, 26, 53, 183, 76, 213, 126, 215, 249, 57,
        47, 254, 127, 202, 29, 189,
    ];

    let recv_pubkey = secp256k1_recover(&hashed_msg_with_prefix[..], recovery_id, &sig)
        .expect("Failed to recover public key");
    let expected_key = &pubkey[1..]; // [X || Y], 64 bytes

    assert_eq!(
        recv_pubkey.to_bytes(),
        expected_key,
        "Recovered public key does not match the expected key"
    );
}
