[package]
name = "perun-solana-program"
authors = ["PolyCrypt GmbH <info@polycry.pt>"]
repository = "https://github.com/perun-network/perun-solana-program"
description = " Perun state channel program on Solana"
readme = "README.md"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
alloy-sol-macro = "0.7.7"
alloy-sol-types = { version = "0.7.7", default-features = false }
alloy-primitives = { version = "0.7.7", default-features = false }
borsh = { version = "1.5.7", features = ["derive"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
solana-program = "2.2.1"
thiserror = "2.0.12"


[dev-dependencies]
base64ct = "=1.6.0"
sha3 = "0.10.8"
k256 = "=0.13.1"
