cargo-features = ["edition2024"]

[package]
name = "perun-solana-program"
authors = ["PolyCrypt GmbH <info@polycry.pt>"]
repository = "https://github.com/perun-network/perun-solana-program"
description = " Perun state channel program on Solana"
readme = "README.md"
version = "0.1.0"
edition = "2024"

[features]
no-entrypoint = []
test-sbf = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
alloy = "1.0.9"
borsh = { version = "1.5.7", features = ["derive"] }
k256 = "0.13.4"
num-derive = "0.4.2"
num-traits = "0.2.19"
sha3 = "0.10.8"
solana-program = "2.2.1"
thiserror = "2.0.12"
